### ISSUE TITLE
Sign in or Create an account translates to Ingresar o Create an account

### ISSUE THREAD

**Issue by javiermartinezruiz** [cniebla/magento2-es_mx#52]
The translation from Store front at top right is incomplete.
It translates Ingresar o Create an account.
![screen shot 2016-09-18 at 1 08 06 pm](https://cloud.githubusercontent.com/assets/14191985/18617898/f7e75880-7da0-11e6-939c-8d8b99db67a9.png)

**Comment by cniebla** [comment]
No pude replicar el mensaje, quizás el browser está en default de idioma -> inglés?
