### ISSUE TITLE
¿Traducción del panel de administración?

### ISSUE THREAD

**Issue by vmsoftware** [cniebla/magento2-es_mx#63]
Muchas gracias por el paquete, excelente trabajo.

Hice la instalación tal como aqui se explica y funciona correctamente en el fontend pero el backend sigue en ingles, No estoy seguro si debo realizar alguna configuración adicional o si hace falta realizar la traducción de dicho apartado.

gracias!

**Comment by cniebla** [comment]
Cerrando por abandono de proyecto.
