### ISSUE TITLE
How to address a person (tú / usted)

### ISSUE THREAD

**Issue by cniebla** [cniebla/magento2-es_mx#8]
In english, you could address a person mostly using the 1st person (e.g. you). In spanish, you can address a person by using the 1st. person in two ways, one _coloquial_ (tú) and one as a sign of _respect_ (usted). There was a decision to use the later (usted). But this could alter the tone of stores directed to younger people. If there's a certain amount of interest, we could produce a separate pack in the coloquial form (tú).

En inglés, uno se dirije casi siempre usando la 1a. persona (you). En español, se puede usar la 1a. persona de 2 formas, una _coloquial_ (tú) y otra como signo de _respeto_ (usted). Se tomó la decisión de usar la última (usted). Pero esto puede alterar el tono en tiendas dirigidas al público joven. Si existe el suficiente interés, podríamos producir un paquete de lenguaje separado en la forma coloquial (tú).

**Comment by maxedout** [comment]
Usted is the formal, non-friend way of addressing someone. At least that is how I learned it. I guess it would come down to how friendly your are trying to be with your clients ;)

I would say usted is right for this. but it is very contextual
